export const START_NEW_PUZZLE = "START_NEW_PUZZLE";
export const CHANGE_GRID_SIZE = "CHANGE_GRID_SIZE";
export const CHANGE_DISPLAY_TYPE = "CHANGE_DISPLAY_TYPE";
export const GRAB_TILE = "GRAB_TILE";
export const DRAG_TILE = "DRAG_TILE";
export const DROP_TILE = "DROP_TILE";
export const START_MOVE = "START_MOVE";
export const END_MOVE = "END_MOVE";
export const REQUEST_SOLUTION = "REQUEST_SOLUTION";
export const RECEIVE_SOLUTION = "RECEIVE_SOLUTION";
export const RESIZE_GAME = "RESIZE_GAME";

