export const START_NEW_PUZZLE = "START_NEW_PUZZLE";
export const CHANGE_GRID_SIZE = "CHANGE_GRID_SIZE";
export const CHANGE_DISPLAY_TYPE = "CHANGE_DISPLAY_TYPE";
export const GRAB_TILE = "GRAB_TILE";
export const DRAG_TILE = "DRAG_TILE";
export const DROP_TILE = "DROP_TILE";
export const START_SOLUTION_MOVE = "START_SOLUTION_MOVE";
export const END_SOLUTION_MOVE = "END_SOLUTION_MOVE";
export const SOLUTION_COMPLETE = "SOLUTION_COMPLETE";
export const REQUEST_SOLUTION = "REQUEST_SOLUTION";
export const RECEIVE_SOLUTION = "RECEIVE_SOLUTION";
export const RESIZE_GAME = "RESIZE_GAME";
export const ADD_IMAGES = "ADD_IMAGES";
export const SET_DEFAULT_IMAGE = "SET_DEFAULT_IMAGE";

